---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Setup additional yum packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - yum-utils
      - centos-release-scl

- name: setup devtoolset-7-gcc
  yum:
    name: devtoolset-7-gcc*
    update_cache: yes
    enablerepo: centos-sclo-rh-testing
    state: present

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql16
    - percona-postgresql16-contrib
    - percona-postgresql16-devel
    - percona-postgresql16-libs
    - percona-postgresql16-llvmjit
    - percona-postgresql16-plperl
    - percona-postgresql16-plpython3
    - percona-postgresql16-pltcl
    - percona-postgresql16-server
    - percona-postgresql16-test
    - openssl-devel
    - llvm-toolset-7-clang
    - llvm5.0
    - llvm-toolset-7
    - readline-devel
    - gcc
    - gcc-c++
    - lz4
    - lz4-devel
    - zstd
    - libzstd-devel
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-16/bin/initdb -A trust -k /var/lib/pgsql/16/data
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  become_user: postgres

- name: Enable gcc 7
  shell: echo "source /opt/rh/devtoolset-7/enable" | sudo tee -a /etc/profile;

- name: Set source
  shell: source /opt/rh/devtoolset-7/enable;

- name: Delete old gcc
  shell: rm /usr/bin/gcc

- name: Set symbol link
  shell: ln -s /opt/rh/devtoolset-7/root/usr/bin/gcc /usr/bin/gcc

- name: Clone pg_repack sources
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /tmp/pg_repack
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"
  become_user: postgres

- name: Build pg_repack from sources
  make:
    target: install
    chdir: "/tmp/pg_repack"
    params:
      USE_PGXS: 1

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/pgsql-16/bin/pg_repack
    dest: /usr/bin/pg_repack
    state: link

- name: Start Postgres RHEL
  service:
    name: postgresql-16
    state: started
    enabled: yes
