---
# Tasks for test major upgrade for PPG 15 packages

- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 14 packages
  include_tasks: ../../../../tasks/install_ppg14.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-14/bin/postgresql-14-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg14_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-14
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - percona-postgresql
      - percona-postgresql-15
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-15
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-15
      - percona-postgresql-plperl-15
      - percona-postgresql-plpython3-15
      - percona-postgresql-pltcl-15
      - percona-postgresql-server-dev-15
      - percona-postgresql-server-dev-all
      - percona-postgresql-15-dbgsym
      - percona-postgresql-client-15-dbgsym
      - percona-postgresql-plperl-15-dbgsym
      - percona-postgresql-plpython3-15-dbgsym
      - percona-postgresql-pltcl-15-dbgsym
  when: ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql-plpython3-15
    - percona-postgresql-plpython3-15-dbgsym
  when:
    - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql15
      - percona-postgresql15-contrib
      - percona-postgresql15-debuginfo
      - percona-postgresql15-devel
      - percona-postgresql15-docs
      - percona-postgresql15-libs
      - percona-postgresql15-llvmjit
      - percona-postgresql15-plperl
      - percona-postgresql15-plpython3
      - percona-postgresql15-pltcl
      - percona-postgresql15-server
      - percona-postgresql15-test
      - percona-postgresql15-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql15
        - percona-postgresql15-contrib
        - percona-postgresql15-debuginfo
        - percona-postgresql15-devel
        - percona-postgresql15-docs
        - percona-postgresql15-libs
        - percona-postgresql15-llvmjit
        - percona-postgresql15-plpython3
        - percona-postgresql15-plperl
        - percona-postgresql15-pltcl
        - percona-postgresql15-server
        - percona-postgresql15-test
        - percona-postgresql15-contrib-debuginfo
        - percona-postgresql15-debuginfo
        - percona-postgresql15-debugsource
        - percona-postgresql15-devel-debuginfo
        - percona-postgresql15-libs-debuginfo
        - percona-postgresql15-plperl-debuginfo
        - percona-postgresql15-pltcl-debuginfo
        - percona-postgresql15-plpython3-debuginfo
        - percona-postgresql15-server-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-14
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- pause:
    minutes: 1

- name: Execute pg_upgrade RHEL
  command: /usr/pgsql-15/bin/pg_upgrade --old-bindir /usr/pgsql-14/bin --new-bindir /usr/pgsql-15/bin --old-datadir /var/lib/pgsql/14/data --new-datadir /var/lib/pgsql/15/data
  become: true
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "RedHat"

- name: Execute pg_upgrade Deb
  command: /usr/lib/postgresql/15/bin/pg_upgrade --old-datadir=/var/lib/postgresql/14/main --new-datadir=/var/lib/postgresql/15/main --old-bindir=/usr/lib/postgresql/14/bin --new-bindir=/usr/lib/postgresql/15/bin --old-options '-c config_file=/etc/postgresql/14/main/postgresql.conf' --new-options '-c config_file=/etc/postgresql/15/main/postgresql.conf'
  become: true
  become_method: sudo
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "Debian"

- name: Change postgresql 14 port in config Debian
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "Debian"

- name: Change postgresql 14 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/14/data/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "RedHat"

- name: Change postgresql 15 port in config Debian
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "Debian"

- name: Change postgresql 15 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/15/data/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for RHEL based
  service:
    name: postgresql-15
    state: restarted
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for Debian based
  service:
    name: postgresql
    state: restarted
    enabled: true
  when: ansible_os_family == "Debian"

- name: Upgrade debian development packages
  apt:
    update_cache: yes
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - libecpg6
      - libecpg-compat3
      - libecpg6
      - libecpg-dev
      - libpgtypes3
      - libpq-dev
      - libpq5
  when: ansible_os_family == "Debian"

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir
