---
- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install Percona Platform for PostgreSQL 15 packages
  include_tasks: ../../../../tasks/install_ppg_meta_server.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-15
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"