listen_addresses = '*'
port = 9999
unix_socket_directories = '/var/run/postgresql'

backend_clustering_mode = 'streaming_replication'

backend_hostname0 = '127.0.0.1'
backend_port0 = 5432
backend_weight0 = 1
backend_data_directory0 = '/tmp/data1'

backend_hostname1 = '127.0.0.1'
backend_port1 = 5433
backend_weight1 = 1
backend_data_directory1 = '/tmp/data2'

load_balance_mode = on

sr_check_period = 10
sr_check_user = 'monitor'
sr_check_password = 'Monitor@321'
sr_check_database = 'monitor'

log_destination = 'stderr'
logging_collector = on
log_directory = '/var/log/pgpool_log'
