---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-11
          - percona-patroni
      when: ansible_distribution == "Debian"

    - name: remove patroni ubuntu
      apt:
        name: percona-patroni
        state: absent
      when: ansible_distribution == "Ubuntu"
