---
- name: Fix broken
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Fix Postgresql-14 deb packages
      apt:
        name: "{{ packages }}"
        state: fixed
        update_cache: true
      vars:
        packages:
          - percona-postgresql-14
          - percona-postgresql-14-dbgsym
          - percona-postgresql-client-14
          - percona-postgresql-doc-14
          - percona-postgresql-plperl-14
          - percona-postgresql-plpython3-14
          - percona-postgresql-pltcl-14
          - percona-postgresql-server-dev-14
          - percona-postgresql-client-14-dbgsym
          - percona-postgresql-plperl-14-dbgsym
          - percona-postgresql-plpython3-14-dbgsym
          - percona-postgresql-pltcl-14-dbgsym
          - percona-pg-stat-monitor14
          - percona-pgaudit14-set-user
          - percona-postgresql-14-wal2json
      when: ansible_os_family == "Debian"

- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
        update_cache: true
      vars:
        packages:
          - percona-postgresql-14
          - percona-postgresql-14-dbgsym
          - percona-postgresql-client-14
          - percona-postgresql-doc-14
          - percona-postgresql-plperl-14
          - percona-postgresql-plpython3-14
          - percona-postgresql-pltcl-14
          - percona-postgresql-server-dev-14
          - percona-postgresql-client-14-dbgsym
          - percona-postgresql-plperl-14-dbgsym
          - percona-postgresql-plpython3-14-dbgsym
          - percona-postgresql-pltcl-14-dbgsym
          - percona-pg-stat-monitor14
          - percona-pgaudit14-set-user
          - percona-postgresql-14-wal2json
      ignore_errors: true
      when: ansible_os_family == "Debian"

    # - name: Remove Percona Platform for PostgreSQL deb packages
    #   apt:
    #     name: "{{ packages }}"
    #     state: absent
    #   vars:
    #     packages:
    #     - percona-postgresql-plpython-14
    #     - percona-postgresql-plpython-14-dbgsym
    #     - percona-postgresql-server-dev-14-dbgsym
    #   when:
    #     - ansible_os_family == "Debian"
    #     - lookup('env', 'PG_VERSION') == "ppg-14.5"

    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql14
          - percona-postgresql14
          - percona-postgresql14-contrib
          - percona-postgresql14-debuginfo
          - percona-postgresql14-devel
          - percona-postgresql14-docs
          - percona-postgresql14-libs
          - percona-postgresql14-llvmjit
          - percona-postgresql14-plperl
          - percona-postgresql14-plpython
          - percona-postgresql14-pltcl
          - percona-postgresql14-server
          - percona-postgresql14-test
          - percona-postgresql14-debuginfo
          - percona-postgresql14-debugsource
          - percona-postgresql14-devel-debuginfo
          - percona-postgresql14-libs-debuginfo
          - percona-postgresql14-plperl-debuginfo
          - percona-postgresql14-plpython-debuginfo
          - percona-postgresql14-plpython3-debuginfo
          - percona-postgresql14-pltcl-debuginfo
          - percona-postgresql14-server-debuginfo
      when: ansible_os_family == "RedHat"

    # - name: remove pgaudit deb packages
    #   apt:
    #     name: percona-postgresql-14-pgaudit
    #     state: absent
    #   when: ansible_os_family == "Debian"

    # - name: remove pg_repack deb packages
    #   apt:
    #     name: "{{ packages }}"
    #     state: absent
    #   vars:
    #     packages:
    #       - percona-postgresql-14-repack
    #       - percona-postgresql-14-repack-dbgsym
    #   when: ansible_os_family == "Debian"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack14
        state: absent
      when: ansible_os_family == "RedHat"
