---
- name: Run pgaudit tests
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: true
  tasks:
    - name: Test pgaudit
      make:
        target: installcheck
        chdir: "/tmp/pg_audit"
        params:
          USE_PGXS: 1
      become_user: postgres
      register: installcheck

    - debug: var=installcheck.stdout_lines

