---
  - set_fact:
      version: "{{ lookup('env', 'VERSION').split('.')[0].split('-')[1] }}"

  - name: Clean dnf RHEL8
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable dnf module for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset dnf module for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install Postgresql Server meta package Debian
    apt:
      name: percona-ppg-server-{{ version }}
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Install Postgresql Server meta package RHEL
    yum:
      name: percona-ppg-server{{ version }}
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"
