---
  - set_fact:
      version: "{{ lookup('env', 'VERSION').split('.')[0].split('-')[1] }}"

  - name: Install Postgresql Server meta HA package Debian
    apt:
      name: percona-ppg-server-ha-{{ version }}
      state: latest
    when: ansible_os_family == "Debian"

  - name: Install Postgresql Server meta HA package RHEL
    yum:
      name: percona-ppg-server-ha{{ version }}
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"
