
  - name: Set Facts.
    set_fact:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      cacheable: true

  - debug:
      msg: "Value of PERCONA_TELEMETRY_URL is : {{ PERCONA_TELEMETRY_URL }}"

  - name: Clean dnf
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat"

  - name: Disable dnf postgresql for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-19
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-19
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-19
      - percona-postgresql-plperl-19
      - percona-postgresql-plpython3-19
      - percona-postgresql-pltcl-19
      - percona-postgresql-server-dev-19
      - percona-postgresql-server-dev-all
      - percona-postgresql-19-dbgsym
      - percona-postgresql-client-19-dbgsym
      - percona-postgresql-plperl-19-dbgsym
      - percona-postgresql-plpython3-19-dbgsym
      - percona-postgresql-pltcl-19-dbgsym
      - postgresql-client-common
      - postgresql-common
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql-plpython3-19
      - percona-postgresql-plpython3-19-dbgsym
    when:
      - ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql19
        - percona-postgresql19-contrib
        - percona-postgresql19-debuginfo
        - percona-postgresql19-devel
        - percona-postgresql19-docs
        - percona-postgresql19-libs
        - percona-postgresql19-llvmjit
        - percona-postgresql19-plpython3
        - percona-postgresql19-plperl
        - percona-postgresql19-pltcl
        - percona-postgresql19-server
        - percona-postgresql19-test
        - percona-postgresql19-contrib-debuginfo
        - percona-postgresql19-debuginfo
        - percona-postgresql19-debugsource
        - percona-postgresql19-devel-debuginfo
        - percona-postgresql19-libs-debuginfo
        - percona-postgresql19-plperl-debuginfo
        - percona-postgresql19-pltcl-debuginfo
        - percona-postgresql19-plpython3-debuginfo
        - percona-postgresql19-server-debuginfo
        - percona-postgresql-common-dev
    when: ansible_os_family == "RedHat"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
