  - name: setup epel release
    yum:
      name: epel-release
      update_cache: yes
      state: present
    when: ansible_os_family == "RedHat"

  - name: Clean dnf RHEL8
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable powertools RHEL8
    become: true
    command: dnf config-manager --set-enabled powertools
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Find all of the files inside /etc/yum.repos.d directory
    find:
      paths: "/etc/yum.repos.d/"
      patterns: "*.repo"
    register: repos

  - name: Comment 'mirrorlist' in /etc/yum.repos.d/*.repo files
    replace:
      path: "{{ item.path }}"
      regexp: 'mirrorlist'
      replace: '#mirrorlist'
    with_items: "{{ repos.files }}"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Replace 'baseurl' in /etc/yum.repos.d/*.repo files
    replace:
      path: "{{ item.path }}"
      regexp: '#baseurl=http://mirror.centos.org'
      replace: 'baseurl=http://vault.centos.org'
    with_items: "{{ repos.files }}"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Update dnf RHEL8
    become: true
    command: dnf update -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable dnf module for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset dnf module for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-13
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-13
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-13
      - percona-postgresql-plperl-13
      - percona-postgresql-plpython3-13
      - percona-postgresql-pltcl-13
      - percona-postgresql-server-dev-13
      - percona-postgresql-server-dev-all
      - percona-postgresql-13-dbgsym
      - percona-postgresql-client-13-dbgsym
      - percona-postgresql-plperl-13-dbgsym
      - percona-postgresql-plpython3-13-dbgsym
      - percona-postgresql-pltcl-13-dbgsym
    when: ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql-plpython3-13
      - percona-postgresql-plpython3-13-dbgsym
    when:
      - ansible_os_family == "Debian"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql13
      - percona-postgresql13-contrib
      - percona-postgresql13-debuginfo
      - percona-postgresql13-devel
      - percona-postgresql13-docs
      - percona-postgresql13-libs
      - percona-postgresql13-llvmjit
      - percona-postgresql13-plperl
      - percona-postgresql13-plpython3
      - percona-postgresql13-pltcl
      - percona-postgresql13-server
      - percona-postgresql13-test
      - percona-postgresql13-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql13
        - percona-postgresql13-contrib
        - percona-postgresql13-debuginfo
        - percona-postgresql13-devel
        - percona-postgresql13-docs
        - percona-postgresql13-libs
        - percona-postgresql13-llvmjit
        - percona-postgresql13-plpython3
        - percona-postgresql13-plperl
        - percona-postgresql13-pltcl
        - percona-postgresql13-server
        - percona-postgresql13-test
        - percona-postgresql13-contrib-debuginfo
        - percona-postgresql13-debuginfo
        - percona-postgresql13-debugsource
        - percona-postgresql13-devel-debuginfo
        - percona-postgresql13-libs-debuginfo
        - percona-postgresql13-plperl-debuginfo
        - percona-postgresql13-pltcl-debuginfo
        - percona-postgresql13-plpython3-debuginfo
        - percona-postgresql13-server-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
