
  - name: Set Facts.
    set_fact:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      cacheable: true

  - debug:
      msg: "Value of PERCONA_TELEMETRY_URL is : {{ PERCONA_TELEMETRY_URL }}"

  - name: setup epel release
    yum:
      name: epel-release
      update_cache: yes
      state: present
    when: ansible_os_family == "RedHat"

  - name: Clean dnf rocky linux
    become: true
    command: dnf clean all -y
    when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")

  - name: Enable powertools on rocky linux 8
    become: true
    command: dnf config-manager --set-enabled powertools
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable powertools on rocky linux 9
    become: true
    command: dnf config-manager --set-enabled crb
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: Disable postgresql module for RHEL8
    become: true
    command: dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Disable llvm-toolset for RHEL8
    become: true
    command: dnf module disable llvm-toolset -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql
      - percona-postgresql-11
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-11
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-11
      - percona-postgresql-plperl-11
      - percona-postgresql-plpython3-11
      - percona-postgresql-pltcl-11
      - percona-postgresql-server-dev-11
      - percona-postgresql-server-dev-all
      - percona-postgresql-11-dbgsym
      - percona-postgresql-client-11-dbgsym
      - percona-postgresql-plperl-11-dbgsym
      - percona-postgresql-plpython3-11-dbgsym
      - percona-postgresql-pltcl-11-dbgsym
      - postgresql-common
      - postgresql-client-common
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-postgresql-plpython-11
      - percona-postgresql-plpython-11-dbgsym
      - percona-postgresql-server-dev-11-dbgsym
    when:
      - ansible_os_family == "Debian"
      - lookup('env', 'PG_VERSION') == "ppg-11.5"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql11
      - percona-postgresql11-contrib
      - percona-postgresql11-debuginfo
      - percona-postgresql11-devel
      - percona-postgresql11-docs
      - percona-postgresql11-libs
      - percona-postgresql11-llvmjit
      - percona-postgresql11-plperl
      - percona-postgresql11-plpython
      - percona-postgresql11-plpython3
      - percona-postgresql11-pltcl
      - percona-postgresql11-server
      - percona-postgresql11-test
      - percona-postgresql11-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql11
        - percona-postgresql11-contrib
        - percona-postgresql11-debuginfo
        - percona-postgresql11-devel
        - percona-postgresql11-docs
        - percona-postgresql11-libs
        - percona-postgresql11-llvmjit
        - percona-postgresql11-plperl
        - percona-postgresql11-plpython
        - percona-postgresql11-plpython3
        - percona-postgresql11-pltcl
        - percona-postgresql11-server
        - percona-postgresql11-test
        - percona-postgresql11-contrib-debuginfo
        - percona-postgresql11-debuginfo
        - percona-postgresql11-debugsource
        - percona-postgresql11-devel-debuginfo
        - percona-postgresql11-libs-debuginfo
        - percona-postgresql11-plperl-debuginfo
        - percona-postgresql11-plpython-debuginfo
        - percona-postgresql11-plpython3-debuginfo
        - percona-postgresql11-pltcl-debuginfo
        - percona-postgresql11-server-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: install Percona Platform for PostgreSQL rpm packages for RHEL
    yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql11
        - percona-postgresql11-contrib
        - percona-postgresql11-debuginfo
        - percona-postgresql11-devel
        - percona-postgresql11-docs
        - percona-postgresql11-libs
        - percona-postgresql11-llvmjit
        - percona-postgresql11-plperl
        - percona-postgresql11-plpython3
        - percona-postgresql11-pltcl
        - percona-postgresql11-server
        - percona-postgresql11-test
        - percona-postgresql11-contrib-debuginfo
        - percona-postgresql11-debuginfo
        - percona-postgresql11-debugsource
        - percona-postgresql11-devel-debuginfo
        - percona-postgresql11-libs-debuginfo
        - percona-postgresql11-plperl-debuginfo
        - percona-postgresql11-plpython3-debuginfo
        - percona-postgresql11-pltcl-debuginfo
        - percona-postgresql11-server-debuginfo
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  - name: Check if Telemetry file exisits
    stat:
        path: /usr/local/percona/telemetry_uuid
    register: telemetry_file_check

  - name: Register output of /usr/local/percona/telemetry_uuid
    become: true
    command: cat /usr/local/percona/telemetry_uuid
    register: telemetry_file_output
    when: telemetry_file_check.stat.exists

  - debug:
      msg: "Telemetry file output is : {{ telemetry_file_output }}"
    when: telemetry_file_check.stat.exists
