  - name: install GPG key for Postgresql repos
    rpm_key:
      state: present
      key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
      validate_certs: false
    when: ansible_os_family == "RedHat"

  - name: postgresql key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
    when: ansible_os_family == "Debian"

  - name: create variable
    command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
    register: repo_line
    when: ansible_os_family == "Debian"

  - name: add postgresql repo
    apt_repository:
      repo: "{{ repo_line.stdout }}"
      state: present
    when: ansible_os_family == "Debian"

  - name: DNF disable postgresql RHEL
    command: sudo dnf module disable postgresql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable powertools on rocky linux 8
    become: true
    command: dnf config-manager --set-enabled powertools
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Enable crb on rocky linux 9
    become: true
    command: dnf config-manager --set-enabled crb
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: DNF clean RHEL
    command: sudo dnf clean all -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Add PostgreSQL YUM Repository RHEL7
    yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm state=present validate_certs=false
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Add PostgreSQL YUM Repository RHEL8
    yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm state=present validate_certs=false
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Add PostgreSQL YUM Repository RHEL9
    yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm state=present validate_certs=false
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

  - name: Install vanila postgres RHEL
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - postgresql11
        - postgresql11-server
        - postgresql11-contrib
        - postgresql-contrib
    when: ansible_os_family == "RedHat"

  - name: Install vanila postgres DEB
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - postgresql-11
    when: ansible_os_family == "Debian"
