---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: pgtde-centos7-${BUILD_NUMBER}
    region: eu-central-1
    image: ami-095e1a4d3d632d215
    vpc_subnet_id: subnet-085deaca8c1c59a4f
    instance_type: t2.xlarge
    ssh_user: centos
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
    verify: ../../playbooks/verify.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
