---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: pgtde-debian11-arm-${BUILD_NUMBER}
    region: eu-central-1
    image: ami-0f41d093198bfb6d5
    vpc_subnet_id: subnet-0fad4db6fdd8025b6
    instance_type: t4g.xlarge
    ssh_user: admin
    root_device_name: /dev/xvda
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: ansible
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
