---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-16
          - percona-postgresql-16-pgaudit
          - percona-postgresql-16-repack
          - percona-postgresql-16-wal2json
          - percona-pg-stat-monitor16
      when: ansible_distribution == "Debian"
