---
# Tasks for test major upgrade for PPG 16 packages

- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    pg_version_to_install: "{{ lookup('env', 'FROM_VERSION') | replace('ppg-','') }}"

- name: End play on oracle linux 9
  meta: end_play
  when: ansible_os_family == "RedHat" and
   ansible_distribution_major_version == "9" and
   pg_version_to_install | string is version('15.2', '<=', strict=True)

- name: End play on Debian 12
  meta: end_play
  when: ansible_os_family == "Debian" and
   ansible_distribution_major_version == "12" and
   pg_version_to_install | string is version('15.3', '<=', strict=True)

- name: End play on Ubuntu 24
  meta: end_play
  when: ansible_distribution == "Ubuntu" and
   ansible_distribution_major_version == "24" and
   pg_version_to_install | string is version('15.6', '<=', strict=True)

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 15 packages
  include_tasks: ../../../../tasks/install_ppg15.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg15_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-15
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable-only {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - percona-postgresql
      - percona-postgresql-16
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-16
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-16
      - percona-postgresql-plperl-16
      - percona-postgresql-plpython3-16
      - percona-postgresql-pltcl-16
      - percona-postgresql-server-dev-16
      - percona-postgresql-server-dev-all
      - percona-postgresql-16-dbgsym
      - percona-postgresql-client-16-dbgsym
      - percona-postgresql-plperl-16-dbgsym
      - percona-postgresql-plpython3-16-dbgsym
      - percona-postgresql-pltcl-16-dbgsym
      - postgresql-client-common
      - postgresql-common
  when: ansible_os_family == "Debian"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

# - name: install Percona Platform for PostgreSQL deb packages
#   apt:
#     name: "{{ packages }}"
#     update_cache: yes
#     state: latest
#   vars:
#     packages:
#     - percona-postgresql-plpython3-16
#     - percona-postgresql-plpython3-16-dbgsym
#   when:
#     - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql16
      - percona-postgresql16-contrib
      - percona-postgresql16-debuginfo
      - percona-postgresql16-devel
      - percona-postgresql16-docs
      - percona-postgresql16-libs
      - percona-postgresql16-llvmjit
      - percona-postgresql16-plperl
      - percona-postgresql16-plpython3
      - percona-postgresql16-pltcl
      - percona-postgresql16-server
      - percona-postgresql16-test
      - percona-postgresql16-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Disable llvm-toolset dnf module for RHEL8
  become: true
  command: dnf module disable llvm-toolset -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-server-dev-all
        - percona-postgresql16
        - percona-postgresql16-contrib
        - percona-postgresql16-debuginfo
        - percona-postgresql16-devel
        - percona-postgresql16-docs
        - percona-postgresql16-libs
        - percona-postgresql16-llvmjit
        - percona-postgresql16-plpython3
        - percona-postgresql16-plperl
        - percona-postgresql16-pltcl
        - percona-postgresql16-server
        - percona-postgresql16-test
        - percona-postgresql16-contrib-debuginfo
        - percona-postgresql16-debuginfo
        - percona-postgresql16-debugsource
        - percona-postgresql16-devel-debuginfo
        - percona-postgresql16-libs-debuginfo
        - percona-postgresql16-plperl-debuginfo
        - percona-postgresql16-pltcl-debuginfo
        - percona-postgresql16-plpython3-debuginfo
        - percona-postgresql16-server-debuginfo
  when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Install pg-stat-monitor RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-pg_stat_monitor16
  when: ansible_os_family == "RedHat"

- name: Install pg-stat-monitor debian
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-pg-stat-monitor16
  when: ansible_os_family == "Debian"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-16/bin/postgresql-16-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-15
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- pause:
    minutes: 1

- name: Execute pg_upgrade RHEL
  command: /usr/pgsql-16/bin/pg_upgrade --old-bindir /usr/pgsql-15/bin --new-bindir /usr/pgsql-16/bin --old-datadir /var/lib/pgsql/15/data --new-datadir /var/lib/pgsql/16/data
  become: true
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "RedHat"

- name: Execute pg_upgrade Deb
  command: /usr/lib/postgresql/16/bin/pg_upgrade --old-datadir=/var/lib/postgresql/15/main --new-datadir=/var/lib/postgresql/16/main --old-bindir=/usr/lib/postgresql/15/bin --new-bindir=/usr/lib/postgresql/16/bin --old-options '-c config_file=/etc/postgresql/15/main/postgresql.conf' --new-options '-c config_file=/etc/postgresql/16/main/postgresql.conf'
  become: true
  become_method: sudo
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "Debian"

- name: Change postgresql 15 port in config Debian
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "Debian"

- name: Change postgresql 15 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/15/data/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "RedHat"

- name: Change postgresql 16 port in config Debian
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "Debian"

- name: Change postgresql 16 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/16/data/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "RedHat"

- name: Add extensions to postgresql.conf for Debian
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "Debian"

- name: Add extensions to postgresql.conf for RHEL
  lineinfile:
    path: /var/lib/pgsql/16/data/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for RHEL based
  service:
    name: postgresql-16
    state: restarted
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for Debian based
  service:
    name: postgresql
    state: restarted
    enabled: true
  when: ansible_os_family == "Debian"

- name: Display ppg version
  become_user: postgres
  shell: psql -c "select version()"
  register: results

- debug:
      var: results.stdout