---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql16
          - percona-wal2json16
          - percona-pg-stat-monitor16
          - percona-pgaudit
          - percona-pg_repack16
      when: ansible_os_family == "RedHat"
