FROM ubuntu:jammy
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openssl && \
    rm -rf /var/lib/apt/lists/*
COPY gen_certs.sh /gen_certs.sh
RUN chmod +x /gen_certs.sh
CMD ["/gen_certs.sh"]
