---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-17
          - percona-postgresql-17-pgaudit
          - percona-postgresql-17-repack
          - percona-postgresql-17-wal2json
          - percona-pg-stat-monitor17
      when: ansible_distribution == "Debian"
