---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rocky8-${BUILD_NUMBER}-${JOB_NAME}
    region: eu-central-1
    image: ami-0ef838b0ab2b120cf
    vpc_subnet_id: subnet-085deaca8c1c59a4f
    instance_type: t4g.large
    ssh_user: rocky
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
    cleanup: ../../playbooks/cleanup.yml
verifier:
  name: testinfra
  directory: ../../../tests/tests_ppg/
  options:
    verbose: true
    s: true
    m: upgrade
    junitxml: report.xml
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify