---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install additional packages for running tests with apt
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - make
      - gcc
      - pkg-config
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      - libxml-checker-perl
      - libyaml-perl
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - lcov
      - rsync
      - zlib1g-dev
      - libssl-dev
      - libxml2-dev
      - libpq-dev
      - valgrind
      - liblz4-dev
      - liblz4-tool
      - zstd
      - libzstd-dev
      - bzip2
      - libbz2-dev
      - libyaml-dev
      - meson
      - libz-dev
      - libyaml-dev
      - libssh2-1-dev
      - psmisc
  retries: 60
  delay: 10
  register: result
  until: result is not failed

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql
    - percona-postgresql-14
    - percona-postgresql-all
    - percona-postgresql-client
    - percona-postgresql-client-14
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-contrib
    - percona-postgresql-plperl-14
    - percona-postgresql-plpython3-14
    - percona-postgresql-pltcl-14
    - percona-postgresql-server-dev-14
    - percona-postgresql-server-dev-all

- name: Clone pgbackrest sources
  become_user: postgres
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /tmp/pgbackrest
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"

- name: Add user postgres to sudoers
  user:
    name: postgres
    groups: sudo
    append: yes

- name: Stop Postgres
  service:
    name: postgresql
    state: stopped

- name: Make sure tcp port 80 is free
  become: true
  command: sudo fuser -k 80/tcp
  ignore_errors: true

- name: Run pgbackrest regression
  become_user: postgres
  command: pgbackrest/test/test.pl --psql-bin=/usr/lib/postgresql/14/bin \
    --no-valgrind --log-level-test-file=off --no-coverage-report \
    --module=command --module=storage --vm-out --vm=none --no-coverage --test-path /tmp
  args:
    chdir: "/tmp"
  register: results

- debug:
    var: results.stdout
