---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-15
          - percona-postgresql-all
          - percona-postgresql-client-15
          - percona-postgresql-contrib
          - percona-postgresql-doc
          - percona-postgresql-doc-15
          - percona-postgresql-plperl-15
          - percona-postgresql-plpython3-15
          - percona-postgresql-pltcl-15
          - percona-postgresql-server-dev-15
          - percona-postgresql-server-dev-all
          - percona-postgresql-15-dbgsym
          - percona-postgresql-client-15-dbgsym
          - percona-postgresql-plperl-15-dbgsym
          - percona-postgresql-plpython3-15-dbgsym
          - percona-postgresql-pltcl-15-dbgsym
          - percona-postgresql-15-pgaudit
          - percona-postgresql-15-repack
          - percona-postgresql-15-repack-dbgsym
          - percona-pgbackrest
          - percona-pgbackrest-doc
          - percona-patroni
          - percona-patroni-dbgsym
          - percona-pgbadger
          - percona-pgbouncer
          - percona-pgaudit15-set-user
          - percona-pgaudit15-set-user-dbgsym
          - percona-pgbouncer-dbgsym
          - percona-postgresql-15-wal2json
          - percona-postgresql-15-wal2json-dbgsym
      when: ansible_distribution == "Debian"

    - name: remove patroni ubuntu
      apt:
        name: percona-patroni
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Remove postgresql Debian developer packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - libecpg-compat3
        - libecpg-compat3-dbgsym
        - libecpg-dev-dbgsym
        - libecpg-dev
        - libecpg6-dbgsym
        - libecpg6
        - libpgtypes3
        - libpgtypes3-dbgsym
        - libpq-dev
        - libpq5-dbgsym
        - libpq5
      when: ansible_os_family == "Debian"
