DEB_EXTENSIONS = ["pageinspect",
                    "plpython3u",
                    "pg_visibility",
                    "pg_buffercache",
                    "pgstattuple",
                    "cube",
                    "pgrowlocks",
                    "unaccent",
                    "tsm_system_rows",
                    "intarray",
                    "seg",
                    "xml2",
                    "intagg",
                    "pltcl",
                    "btree_gist",
                    "refint",
                    "tablefunc",
                    "dict_int",
                    "pg_prewarm",
                    "pg_freespacemap",
                    "pg_trgm",
                    "earthdistance",
                    "pltclu",
                    "bloom",
                    "hstore",
                    "pg_stat_statements",
                    "ltree",
                    "lo",
                    "dblink",
                    "dict_xsyn",
                    "isn",
                    "plperlu",
                    "tcn",
                    "sslinfo",
                    "jsonb_plpython3u",
                    "amcheck",
                    "pgcrypto",
                    "fuzzystrmatch",
                    "tsm_system_time",
                    "uuid-ossp",
                    "postgres_fdw",
                    "citext",
                    "moddatetime",
                    "insert_username",
                    "btree_gin",
                    "hstore_plpython3u",
                    "adminpack",
                    "autoinc",
                    "plperl",
                    "pg_stat_monitor"
                    ]

RPM_EXTENSIONS = ["hstore",
                    "adminpack",
                    "amcheck",
                    "cube",
                    "insert_username",
                    "autoinc",
                    "bloom",
                    "earthdistance",
                    "intagg",
                    "btree_gin",
                    "file_fdw",
                    "fuzzystrmatch",
                    "btree_gist",
                    "intarray",
                    "citext",
                    "dblink",
                    "dict_xsyn",
                    "lo",
                    "dict_int",
                    "isn",
                    "ltree",
                    "moddatetime",
                    "pgrowlocks",
                    "pageinspect",
                    "pg_trgm",
                    "tcn",
                    "pgstattuple",
                    "pg_buffercache",
                    "xml2",
                    "postgres_fdw",
                    "pg_freespacemap",
                    "pg_prewarm",
                    "pg_visibility",
                    "refint",
                    "pgcrypto",
                    "pg_stat_statements",
                    "seg",
                    "sslinfo",
                    "tablefunc",
                    "tsm_system_rows",
                    "tsm_system_time",
                    "plperlu",
                    "unaccent",
                    "uuid-ossp",
                    "pltcl",
                    "pltclu",
                    "plperl",
                    "pg_stat_monitor"
                    ]


def get_extensions(distro_type):
    """Return the expected extensions list for a molecule scenario name
    (e.g. "debian-12", "ubuntu-noble", "rhel-9"). One list per package
    family serves every supported PG major (14+) and product (ppg/psp).
    """
    if distro_type.startswith(("debian", "ubuntu")):
        return DEB_EXTENSIONS
    return RPM_EXTENSIONS
