---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql14
          - percona-wal2json14
          - percona-pg-stat-monitor14
          - percona-pgaudit
          - percona-pg_repack14
      when: ansible_os_family == "RedHat"
