---
- name: Clean dnf RHEL8
  become: true
  command: dnf clean all -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Enable ol8_codeready_builder on oracle linux 8
  become: true
  command: dnf config-manager --set-enabled ol8_codeready_builder
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable dnf module for RHEL8
  become: true
  command: dnf module disable postgresql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable llvm-toolset dnf module for RHEL8
  become: true
  command: dnf module disable llvm-toolset -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql12
    - percona-postgresql12-contrib
    - percona-postgresql12-devel
    - percona-postgresql12-libs
    - percona-postgresql12-plpython3
    - percona-postgresql12-pltcl
    - percona-postgresql12-server
    - openssl-devel
    - etcd
    - python3-etcd
    - percona-haproxy
    - percona-patroni
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Install python3 module - patroni[etcd]
  become: true
  command: python3 -m pip install patroni[etcd]
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Create /etc/patroni directory
  file:
    path: /etc/patroni
    state: directory

- name: Create test patroni directory
  file:
    path: /var/lib/pgsql/patroni_test/
    state: directory
    owner: postgres
    group: postgres

- name: Copy postgresql0.yml for patroni service
  copy:
    src: postgresql0.yml
    dest: /etc/patroni/postgresql.yml
    owner: root
    group: root
    mode: 0644

- name: Copy postgresql1.yml for patroni service
  copy:
    src: postgresql1.yml
    dest: /var/lib/pgsql/patroni_test/postgresql1.yml
    owner: postgres
    group: postgres
    mode: 0644

- name: Copy postgresql2.yml for patroni service
  copy:
    src: postgresql2.yml
    dest: /var/lib/pgsql/patroni_test/postgresql2.yml
    owner: postgres
    group: postgres
    mode: 0644

- name: Copy patroni1 service file
  copy:
    src: patroni1.service
    dest: /usr/lib/systemd/system/patroni1.service
    owner: root
    group: root
    mode: 0644

- name: Copy patroni2 service file
  copy:
    src: patroni2.service
    dest: /usr/lib/systemd/system/patroni2.service
    owner: root
    group: root
    mode: 0644

- name: Start etcd
  service:
    name: etcd
    state: started
    enabled: yes

- name: Start patroni
  service:
    name: patroni
    state: started
    enabled: yes

- name: Start patroni1
  service:
    name: patroni1
    state: started
    enabled: yes

- name: Start patroni2
  service:
    name: patroni2
    state: started
    enabled: yes

- name: Copy haproxy.cfg
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Start haproxy
  shell: haproxy -f  /etc/haproxy/haproxy.cfg -D

- name: Pause for 1 minutes
  ansible.builtin.pause:
    minutes: 1
