---
  - name: Set Facts
    set_fact:
      testsuite: "{{ lookup('env', 'TESTSUITE') }}"
      percona_server_version: "{{ lookup('env', 'PERCONA_SERVER_VERSION') }}"
      major_version: "{{ lookup('env', 'VERSION').split('.') }}"
      cacheable: true

  - name: Include Redhat tasks file 
    include_tasks: 
      file: "redhat_tasks.yml"
    when: ansible_os_family == 'RedHat'

  - name: Include Debian tasks file 
    include_tasks: 
      file: "debian_tasks.yml"
    when: ansible_os_family == 'Debian'
