---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: pgstatmon-rhel10-${BUILD_NUMBER}
    region: eu-central-1
    image: ami-01e70a605ecda527e
    vpc_subnet_id: subnet-0fad4db6fdd8025b6
    instance_type: t3.large
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-molecule-rhel
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
    verify: ../../playbooks/verify.yml
verifier:
  name: testinfra
  directory: ../../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
