---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-12
          - percona-postgresql-12-pgaudit
          - percona-postgresql-12-repack
          - percona-postgresql-12-wal2json
          - percona-pg-stat-monitor12
      when: ansible_distribution == "Debian"
