---
# Tasks for test major upgrade for PPG 12 packages

- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 11 packages
  include_tasks: ../../../../tasks/install_ppg11.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg11_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-11
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql-12
    - percona-postgresql-client-12
    - percona-postgresql-doc-12
    - percona-postgresql-plperl-12
    - percona-postgresql-plpython3-12
    - percona-postgresql-pltcl-12
    - percona-postgresql-server-dev-12
    - percona-postgresql-12-dbgsym
    - percona-postgresql-client-12-dbgsym
    - percona-postgresql-plperl-12-dbgsym
    - percona-postgresql-plpython3-12-dbgsym
    - percona-postgresql-pltcl-12-dbgsym
    - percona-postgresql-client-common
    - percona-postgresql-common
  when: ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql-plpython3-12
    - percona-postgresql-plpython3-12-dbgsym
  when:
    - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql12
    - percona-postgresql12-contrib
    - percona-postgresql12-debuginfo
    - percona-postgresql12-devel
    - percona-postgresql12-docs
    - percona-postgresql12-libs
    - percona-postgresql12-llvmjit
    - percona-postgresql12-plperl
    - percona-postgresql12-plpython
    - percona-postgresql12-pltcl
    - percona-postgresql12-server
    - percona-postgresql12-test
    - percona-postgresql12-debuginfo
    - percona-postgresql-client-common
    - percona-postgresql-common
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql12
      - percona-postgresql12-contrib
      - percona-postgresql12-debuginfo
      - percona-postgresql12-devel
      - percona-postgresql12-docs
      - percona-postgresql12-libs
      - percona-postgresql12-llvmjit
      - percona-postgresql12-plperl
      - percona-postgresql12-plpython
      - percona-postgresql12-pltcl
      - percona-postgresql12-server
      - percona-postgresql12-test
      - percona-postgresql12-contrib-debuginfo
      - percona-postgresql12-debuginfo
      - percona-postgresql12-debugsource
      - percona-postgresql12-devel-debuginfo
      - percona-postgresql12-libs-debuginfo
      - percona-postgresql12-plperl-debuginfo
      - percona-postgresql12-plpython-debuginfo
      - percona-postgresql12-plpython3-debuginfo
      - percona-postgresql12-pltcl-debuginfo
      - percona-postgresql12-server-debuginfo
      - percona-postgresql-client-common
      - percona-postgresql-common
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-11
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- pause:
    minutes: 1

- name: Execute pg_upgrade RHEL
  command: /usr/pgsql-12/bin/pg_upgrade --old-bindir /usr/pgsql-11/bin --new-bindir /usr/pgsql-12/bin --old-datadir /var/lib/pgsql/11/data --new-datadir /var/lib/pgsql/12/data
  become: true
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "RedHat"

- name: Execute pg_upgrade Deb
  command: /usr/lib/postgresql/12/bin/pg_upgrade --old-datadir=/var/lib/postgresql/11/main --new-datadir=/var/lib/postgresql/12/main --old-bindir=/usr/lib/postgresql/11/bin --new-bindir=/usr/lib/postgresql/12/bin --old-options '-c config_file=/etc/postgresql/11/main/postgresql.conf' --new-options '-c config_file=/etc/postgresql/12/main/postgresql.conf'
  become: true
  become_method: sudo
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "Debian"

- name: Change postgresql 11 port in config Debian
  blockinfile:
    path: /etc/postgresql/11/main/postgresql.conf
    block: |
      port = 5433
  when: ansible_os_family == "Debian"

- name: Change postgresql 11 port in config RHEL
  blockinfile:
    path: /var/lib/pgsql/11/data/postgresql.conf
    block: |
      port = 5433
  when: ansible_os_family == "RedHat"

- name: Change postgresql 12 port in config Debian
  blockinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    block: |
      port = 5432
  when: ansible_os_family == "Debian"

- name: Change postgresql 12 port in config RHEL
  blockinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    block: |
      port = 5432
  when: ansible_os_family == "RedHat"

- name: Add extensions to postgresql.conf for Debian
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "Debian"

- name: Add extensions to postgresql.conf for RHEL
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for RHEL based
  service:
    name: postgresql-12
    state: restarted
    enabled: true
    masked: no
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for Debian based
  service:
    name: postgresql
    state: restarted
    enabled: true
    masked: no
  when: ansible_os_family == "Debian"

- name: Upgrade debian development packages
  apt:
    update_cache: yes
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
      - libecpg6
      - libecpg-compat3
      - libecpg6
      - libecpg-dev
      - libpgtypes3
      - libpq-dev
      - libpq5
  when: ansible_os_family == "Debian"

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir
