---
# Tasks for test major upgrade for PPG 14 packages

- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    pg_version_to_install: "{{ lookup('env', 'FROM_VERSION') | replace('ppg-','') }}"

- name: End play on rocky linux 9
  meta: end_play
  when: ansible_os_family == "RedHat" and
   ansible_distribution_major_version == "9" and
   pg_version_to_install | string is version('13.9', '<=', strict=True)

- name: End play on Debian 12
  meta: end_play
  when: ansible_os_family == "Debian" and
   ansible_distribution_major_version == "12" and
   pg_version_to_install | string is version('13.11', '<=', strict=True)

- name: End play on Ubuntu 24
  meta: end_play
  when: ansible_distribution == "Ubuntu" and
   ansible_distribution_major_version == "24" and
   pg_version_to_install | string is version('13.14', '<=', strict=True)

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 13 packages
  include_tasks: ../../../../tasks/install_ppg13.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-13/bin/postgresql-13-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg13_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-13
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - percona-postgresql
      - percona-postgresql-14
      - percona-postgresql-all
      - percona-postgresql-client
      - percona-postgresql-client-14
      - percona-postgresql-common
      - percona-postgresql-contrib
      - percona-postgresql-doc
      - percona-postgresql-doc-14
      - percona-postgresql-plperl-14
      - percona-postgresql-plpython3-14
      - percona-postgresql-pltcl-14
      - percona-postgresql-server-dev-14
      - percona-postgresql-common-dev
      - percona-postgresql-14-dbgsym
      - percona-postgresql-client-14-dbgsym
      - percona-postgresql-plperl-14-dbgsym
      - percona-postgresql-plpython3-14-dbgsym
      - percona-postgresql-pltcl-14-dbgsym
      - postgresql-client-common
      - postgresql-common
  when: ansible_os_family == "Debian"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

# - name: install Percona Platform for PostgreSQL deb packages
#   apt:
#     name: "{{ packages }}"
#     update_cache: yes
#     state: latest
#   vars:
#     packages:
#     - percona-postgresql-plpython3-14
#     - percona-postgresql-plpython3-14-dbgsym
#   when:
#     - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql14
      - percona-postgresql14-contrib
      - percona-postgresql14-debuginfo
      - percona-postgresql14-devel
      - percona-postgresql14-docs
      - percona-postgresql14-libs
      - percona-postgresql14-llvmjit
      - percona-postgresql14-plperl
      - percona-postgresql14-plpython3
      - percona-postgresql14-pltcl
      - percona-postgresql14-server
      - percona-postgresql14-test
      - percona-postgresql14-debuginfo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
        - percona-postgresql-client-common
        - percona-postgresql-common
        - percona-postgresql-common-dev
        - percona-postgresql14
        - percona-postgresql14-contrib
        - percona-postgresql14-debuginfo
        - percona-postgresql14-devel
        - percona-postgresql14-docs
        - percona-postgresql14-libs
        - percona-postgresql14-llvmjit
        - percona-postgresql14-plpython3
        - percona-postgresql14-plperl
        - percona-postgresql14-pltcl
        - percona-postgresql14-server
        - percona-postgresql14-test
        - percona-postgresql14-contrib-debuginfo
        - percona-postgresql14-debuginfo
        - percona-postgresql14-debugsource
        - percona-postgresql14-devel-debuginfo
        - percona-postgresql14-libs-debuginfo
        - percona-postgresql14-plperl-debuginfo
        - percona-postgresql14-pltcl-debuginfo
        - percona-postgresql14-plpython3-debuginfo
        - percona-postgresql14-server-debuginfo
  when: ansible_os_family == "RedHat" and
      (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9")
  environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Install pg-stat-monitor RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-pg_stat_monitor14
  when: ansible_os_family == "RedHat"

- name: Install pg-stat-monitor debian
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-pg-stat-monitor14
  when: ansible_os_family == "Debian"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-14/bin/postgresql-14-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-13
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- name: Execute pg_createcluster for version 14
  command: /usr/bin/pg_createcluster 14 main --port=5433
  become: true
  become_method: sudo
  become_user: postgres
  when: ansible_os_family == "Debian"

- pause:
    minutes: 1

- name: Execute pg_upgrade RHEL
  command: /usr/pgsql-14/bin/pg_upgrade --old-bindir /usr/pgsql-13/bin --new-bindir /usr/pgsql-14/bin --old-datadir /var/lib/pgsql/13/data --new-datadir /var/lib/pgsql/14/data
  become: true
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "RedHat"

- name: Execute pg_upgrade Deb
  command: /usr/lib/postgresql/14/bin/pg_upgrade --old-datadir=/var/lib/postgresql/13/main --new-datadir=/var/lib/postgresql/14/main --old-bindir=/usr/lib/postgresql/13/bin --new-bindir=/usr/lib/postgresql/14/bin --old-options '-c config_file=/etc/postgresql/13/main/postgresql.conf' --new-options '-c config_file=/etc/postgresql/14/main/postgresql.conf'
  become: true
  become_method: sudo
  become_user: postgres
  args:
    chdir: /tmp
  when: ansible_os_family == "Debian"

- name: Change postgresql 13 port in config Debian
  lineinfile:
    path: /etc/postgresql/13/main/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "Debian"

- name: Change postgresql 13 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/13/data/postgresql.conf
    search_string: 'port'
    line: port = 5433
  when: ansible_os_family == "RedHat"

- name: Change postgresql 14 port in config Debian
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "Debian"

- name: Change postgresql 14 port in config RHEL
  lineinfile:
    path: /var/lib/pgsql/14/data/postgresql.conf
    search_string: 'port'
    line: port = 5432
  when: ansible_os_family == "RedHat"

- name: Add extensions to postgresql.conf for Debian
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "Debian"

- name: Add extensions to postgresql.conf for RHEL
  lineinfile:
    path: /var/lib/pgsql/14/data/postgresql.conf
    line: shared_preload_libraries = 'pg_stat_monitor'
  when: ansible_os_family == "RedHat"

- name: Restart postgresql service for RHEL based
  service:
    name: postgresql-14
    state: restarted
    enabled: true
  when: ansible_os_family == "RedHat"

- name: list /var/run/postgresql
  command: ls -la /var/run/postgresql
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: list pg_lsclsuters
  command: pg_lsclusters
  become: true
  become_method: sudo
  become_user: postgres
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: Drop pg_dropcluster for version 13
  command: /usr/bin/pg_dropcluster 13 main
  become: true
  become_method: sudo
  become_user: postgres
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: list pg_lsclsuters
  command: pg_lsclusters
  become: true
  become_method: sudo
  become_user: postgres
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: Delete /var/run/postgresql lock and pid file
  command: rm -fr /var/run/postgresql/*
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: list /var/run/postgresql
  command: ls -la /var/run/postgresql/
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: Restart postgresql service for Debian based
  service:
    name: postgresql@14-main.service
    state: started
    enabled: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: list pg_lsclsuters
  command: pg_lsclusters
  become: true
  become_method: sudo
  become_user: postgres
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: Get Service Status
  ansible.builtin.systemd:
    name: "postgresql"
  register: pg_service_status

- debug:
    var: pg_service_status.status.ActiveState

- name: Get Service Status
  ansible.builtin.systemd:
    name: "postgresql@14-main.service"
  register: pg_service_status

- debug:
    var: pg_service_status.status.ActiveState

- name: list /var/run/postgresql
  command: ls -la /var/run/postgresql/
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

# - name: show running process for postgres
#   command: ps -ef | grep -i postgres
#   become: true
#   when: ansible_os_family == "Debian"
#   register: results

# - debug:
#     var: results.stdout_lines

- name: show port for postgres
  command: grep -i port /etc/postgresql/14/main/postgresql.conf
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- name: show pg log 14 for postgres
  ignore_errors: true
  command: cat /var/log/postgresql/postgresql-14-main.log
  become: true
  when: ansible_os_family == "Debian"
  register: results

- debug:
    var: results.stdout_lines

- pause:
    minutes: 1

- name: Display ppg version
  ignore_errors: true
  become_user: postgres
  shell: psql -c "select version();"
  register: results

- debug:
    var: results.stdout_lines
