---
- name: Run set_user tests
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: true
  tasks:
    - name: Test set_user
      make:
        target: installcheck
        chdir: "/tmp/set_user"
        params:
          USE_PGXS: 1
      become_user: postgres
      register: installcheck

    - debug: var=installcheck.stdout_lines

