---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql14
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql-server-dev-all
          - percona-postgresql14
          - percona-postgresql14-contrib
          - percona-postgresql14-debuginfo
          - percona-postgresql14-devel
          - percona-postgresql14-docs
          - percona-postgresql14-libs
          - percona-postgresql14-llvmjit
          - percona-postgresql14-plperl
          - percona-postgresql14-plpython
          - percona-postgresql14-pltcl
          - percona-postgresql14-server
          - percona-postgresql14-test
          - percona-postgresql14-debuginfo
          - percona-postgresql14-debugsource
          - percona-postgresql14-devel-debuginfo
          - percona-postgresql14-libs-debuginfo
          - percona-postgresql14-plperl-debuginfo
          - percona-postgresql14-plpython3-debuginfo
          - percona-postgresql14-pltcl-debuginfo
          - percona-postgresql14-server-debuginfo
          - percona-postgresql14-test-debuginfo
          - percona-pgbadger
          - percona-pgbouncer
          - percona-pgaudit14_set_user
          - percona-wal2json14
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit rpm packages
      yum:
        name: percona-pgaudit
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack14
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pgbackrest rpm packages
      yum:
        name: percona-pgbackrest
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni rpm packages
      yum:
        name: percona-patroni
        state: absent
      when: ansible_os_family == "RedHat"
