---

- hosts: all
  environment:
    PG_TEST_PORT_DIR: /tmp/pg_tde

- name: Run pgtde tests
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: true
  tasks:
    - name: Test pg_tde
      make:
        target: installcheck
        chdir: "/tmp/pg_tde"
        params:
          USE_PGXS: 1
      ignore_errors: yes
      register: installcheck

    - debug: var=installcheck.stdout_lines

    - shell: cat /tmp/pg_tde/regression.diffs
      register: cat

    - name: Display tests diff
      debug: var=cat.stdout_lines
      when: installcheck.rc != 0
      become: true
      become_method: sudo
      become_user: root

    - name: Fail tests on error
      fail:
        msg: Tests failed
      when: installcheck.rc != 0
