---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
        update_cache: yes
      vars:
        packages:
          - percona-postgresql-13
          - percona-postgresql-client-13
          - percona-postgresql-doc-13
          - percona-postgresql-plperl-13
          - percona-postgresql-plpython3-13
          - percona-postgresql-pltcl-13
          - percona-postgresql-server-dev-13
          - percona-postgresql-13-dbgsym
          - percona-postgresql-client-13-dbgsym
          - percona-postgresql-plperl-13-dbgsym
          - percona-postgresql-plpython3-13-dbgsym
          - percona-postgresql-pltcl-13-dbgsym
      ignore_errors: true
      when: ansible_os_family == "Debian"

    - name: Remove Percona Platform for PostgreSQL deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - percona-postgresql-plpython-13
        - percona-postgresql-plpython-13-dbgsym
        - percona-postgresql-server-dev-13-dbgsym
      when:
        - ansible_os_family == "Debian"
        - lookup('env', 'PG_VERSION') == "ppg-13.5"

    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql13
          - percona-postgresql13
          - percona-postgresql13-contrib
          - percona-postgresql13-debuginfo
          - percona-postgresql13-devel
          - percona-postgresql13-docs
          - percona-postgresql13-libs
          - percona-postgresql13-llvmjit
          - percona-postgresql13-plperl
          - percona-postgresql13-plpython
          - percona-postgresql13-pltcl
          - percona-postgresql13-server
          - percona-postgresql13-test
          - percona-postgresql13-debuginfo
          - percona-postgresql13-debugsource
          - percona-postgresql13-devel-debuginfo
          - percona-postgresql13-libs-debuginfo
          - percona-postgresql13-plperl-debuginfo
          - percona-postgresql13-plpython-debuginfo
          - percona-postgresql13-plpython3-debuginfo
          - percona-postgresql13-pltcl-debuginfo
          - percona-postgresql13-server-debuginfo
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit deb packages
      apt:
        name: percona-postgresql-13-pgaudit
        state: absent
      when: ansible_os_family == "Debian"

    - name: remove pg_repack deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-13-repack
          - percona-postgresql-13-repack-dbgsym
      when: ansible_os_family == "Debian"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack13
        state: absent
      when: ansible_os_family == "RedHat"
