"""Generate the versioned ppg role groups (ppg/pg-14..18*, ppg/psp-16*)
from templates/groups/ + ppg/versions.yml.

The groups and tasks/install_ppgXX*.yml are not in git, render.py and
migrate_check.py materialize them through ensure() before they run.

Usage:
  gen_groups.py --write          -- materialize all groups into ppg/
  gen_groups.py --clean          -- remove materialized groups (header check)
  gen_groups.py --list           -- list group dir names
"""
import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

import jinja2
import yaml

HEADER = "# GENERATED by tools/gen_groups.py from ppg/versions.yml -- do not edit\n"

TYPES = {
    "server": "",
    "meta-server": "-meta-server",
    "meta-ha": "-meta-ha",
    "minor-upgrade": "-minor-upgrade",
    "major-upgrade": "-major-upgrade",
}

TEMPLATES = REPO / "templates" / "groups"
TASK_TEMPLATES = REPO / "templates" / "tasks"

_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(TEMPLATES)),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
)

# the shared install task files are full of ansible jinja ({{ packages }}),
# so their templates use different delimiters: << var >> and <% if %>
_task_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(TASK_TEMPLATES)),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
    block_start_string="<%",
    block_end_string="%>",
    variable_start_string="<<",
    variable_end_string=">>",
    comment_start_string="<#",
    comment_end_string="#>",
)


def load_versions():
    return yaml.safe_load((REPO / "ppg" / "versions.yml").read_text())


def render_gate(g):
    if g["action"] == "fail":
        head = 'fail:\n    msg: "%s"' % g["msg"]
    else:
        head = "meta: %s" % g["action"]
    cond = ("ansible_os_family", g["family"]) if "family" in g else \
           ("ansible_distribution", g["distribution"])
    var = g.get("var", "pg_version_to_install")
    return (
        "- name: %s\n"
        "  %s\n"
        '  when: %s == "%s" and\n'
        '    ansible_distribution_major_version == "%s" and\n'
        "    %s | string is version('%s', '%s', strict=True)"
        % (g["name"], head, cond[0], cond[1], g["os_version"], var,
           g["version"], g["op"])
    )


def render_gates(gates):
    return "\n\n".join(render_gate(g) for g in gates)


def group_name(instance, type_name):
    return instance + TYPES[type_name]


def template_files(type_name):
    """Relative output paths for a type, from the template tree."""
    tdir = TEMPLATES / type_name
    out = []
    for p in sorted(tdir.rglob("*.j2")):
        out.append(str(p.relative_to(tdir))[: -len(".j2")])
    return out


def render_context(data, instance, type_name):
    inst = data["instances"][instance]
    ctx = dict(inst.get(type_name) or {})
    ctx.update(
        major=inst["major"],
        prev=inst["major"] - 1,
        flavor=inst["flavor"],
        name=group_name(instance, type_name),
        gates_text=render_gates(ctx.get("gates", [])),
    )
    return ctx


def render_group(data, instance, type_name):
    """Return {relpath: content} for one group dir."""
    ctx = render_context(data, instance, type_name)
    files = {}
    for rel in template_files(type_name):
        tpl = _env.get_template("%s/%s.j2" % (type_name, rel))
        files[rel] = tpl.render(**ctx)
    return files


def all_groups(data):
    for instance in data["instances"]:
        for type_name in TYPES:
            yield instance, type_name


def render_shared_tasks(data):
    """{repo-relative path: content} for tasks/install_ppg<major>*.yml."""
    out = {}
    for instance, inst in data["instances"].items():
        if inst["flavor"] != "ppg":
            continue
        major = inst["major"]
        for tpl_name, target in [
            ("install_ppg.yml.j2", "tasks/install_ppg%d.yml" % major),
            ("install_ppg_tools.yml.j2", "tasks/install_ppg%d_tools.yml" % major),
        ]:
            key = "install" if tpl_name == "install_ppg.yml.j2" else "install_tools"
            ctx = dict(inst.get(key) or {})
            ctx["major"] = major
            out[target] = _task_env.get_template(tpl_name).render(**ctx)
    return out


def is_generated(path):
    if path.name == "__init__.py":
        return path.stat().st_size == 0
    with open(path) as f:
        return f.readline() == HEADER


def write_groups(data):
    for instance, type_name in all_groups(data):
        gdir = REPO / "ppg" / group_name(instance, type_name)
        files = render_group(data, instance, type_name)
        for rel, content in files.items():
            path = gdir / rel
            if path.exists() and not is_generated(path):
                print("refusing to overwrite non-generated file: %s" % path,
                      file=sys.stderr)
                return 2
            path.parent.mkdir(parents=True, exist_ok=True)
            if rel.endswith((".yml", ".yaml")):
                content = HEADER + content
            path.write_text(content)
    for rel, content in render_shared_tasks(data).items():
        path = REPO / rel
        if path.exists() and not is_generated(path):
            print("refusing to overwrite non-generated file: %s" % path,
                  file=sys.stderr)
            return 2
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + content)
    return 0


def clean_groups(data):
    for instance, type_name in all_groups(data):
        gdir = REPO / "ppg" / group_name(instance, type_name)
        if not gdir.is_dir():
            continue
        leftovers = False
        for p in sorted(gdir.rglob("*"), reverse=True):
            if p.is_dir():
                try:
                    p.rmdir()
                except OSError:
                    leftovers = True
            elif is_generated(p):
                p.unlink()
            else:
                print("warning: skipping non-generated file: %s" % p,
                      file=sys.stderr)
                leftovers = True
        if not leftovers:
            try:
                gdir.rmdir()
            except OSError:
                pass
    for rel in render_shared_tasks(data):
        path = REPO / rel
        if not path.exists():
            continue
        if is_generated(path):
            path.unlink()
        else:
            print("warning: skipping non-generated file: %s" % path,
                  file=sys.stderr)
    return 0


def ensure():
    """Materialize all generated groups; render/migrate_check/tests call it."""
    rc = write_groups(load_versions())
    if rc:
        raise RuntimeError("gen_groups.ensure() failed, see stderr")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--clean", action="store_true")
    mode.add_argument("--list", action="store_true")
    args = ap.parse_args(argv)
    data = load_versions()
    if args.list:
        for instance, type_name in all_groups(data):
            print(group_name(instance, type_name))
        return 0
    if args.clean:
        return clean_groups(data)
    return write_groups(data)


if __name__ == "__main__":
    sys.exit(main())
