import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

import jinja2
import yaml

from tools import catalog
from tools.catalog import DEFAULT_CONVERGE, DEFAULT_BILLING_TAG

HEADER = "# GENERATED by tools/render.py from scenario.yml -- do not edit\n"

OVERRIDE_KEYS = {"cleanup", "emit_scenario_name", "billing_tag", "sequences", "aws"}
OVERRIDE_AWS_KEYS = {"size", "subnet", "volume_size"}

_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(REPO / "templates")),
    keep_trailing_newline=True,
)


def resolve_os_key(desc, scenario_name):
    if "scenarios" in desc:
        return desc["scenarios"][scenario_name]["os"]
    return scenario_name


def apply_overrides(desc, scenario_name):
    ov = desc.get("overrides", {}).get(scenario_name)
    if not ov:
        return desc
    desc = dict(desc)
    for k, v in ov.items():
        if k not in OVERRIDE_KEYS:
            raise ValueError("unknown override key %r for scenario %r" % (k, scenario_name))
        if k == "aws":
            if not isinstance(v, dict):
                raise ValueError("aws override for scenario %r must be a dict, got %r" % (scenario_name, v))
            for ak in v:
                if ak not in OVERRIDE_AWS_KEYS:
                    raise ValueError("unknown aws override key %r for scenario %r" % (ak, scenario_name))
            aws = dict(desc.get("aws", {}))
            aws.update(v)
            desc["aws"] = aws
        else:
            desc[k] = v
    return desc


def render_one(group_dir, scenario_name, header=""):
    desc = yaml.safe_load((pathlib.Path(group_dir) / "scenario.yml").read_text())
    os_key = resolve_os_key(desc, scenario_name)
    desc = apply_overrides(desc, scenario_name)
    e = catalog.os_entry(os_key)
    aws = catalog.load("aws.yml")
    arch = "arm" if e["arm"] else "x86"
    token = e["token"] + ("-arm" if e["arm"] else "")
    name = desc["name_pattern"].format(
        token=token, build="${BUILD_NUMBER}", job="${JOB_NAME}", scenario=scenario_name)
    cleanup = desc.get("cleanup", "none")
    if cleanup == "per-family":
        cleanup_playbook = "../../playbooks/cleanup-%s.yml" % e["family"]
    elif cleanup == "shared":
        cleanup_playbook = "../../playbooks/cleanup.yml"
    else:
        cleanup_playbook = None
    subnet_key = desc["aws"]["subnet"]
    if subnet_key not in aws["subnets"]:
        raise KeyError("unknown aws.subnet %r" % subnet_key)
    ctx = dict(
        header=header,
        name=name,
        emit_scenario_name=desc.get("emit_scenario_name", False),
        scenario_dir_name=scenario_name,
        billing_tag=desc.get("billing_tag", DEFAULT_BILLING_TAG),
        # placeholders, not resolved values: local/env.sh maps these to libvirt
        # image-catalog keys, jenkins maps them to AMIs. catalog stays
        # authoritative for the actual values, render just stops inlining them.
        region="${region}",
        image="${ami_%s_%s}" % (e["ami_var"], "arm64" if e["arm"] else "x86_64"),
        subnet_id="${vpc_subnet_id_%s}" % subnet_key,
        instance_type=aws["sizes"][desc["aws"]["size"]][arch],
        ssh_user=e["aws"]["ssh_user"],
        root_device=e["aws"]["root_device"],
        volume_size=desc["aws"].get("volume_size"),
        converge=desc.get("playbooks", {}).get("converge", DEFAULT_CONVERGE),
        cleanup_playbook=cleanup_playbook,
        verifier=desc["verifier"],
        sequences=desc["sequences"],
    )
    return _env.get_template("molecule.yml.j2").render(**ctx)


def expand_scenarios(desc):
    """List of scenario dir names a descriptor renders, in a stable order."""
    if "scenarios" in desc:
        return list(desc["scenarios"])
    ol = desc["os_list"]
    lists = catalog.load("os-lists.yml")
    if isinstance(ol, str):
        return list(lists[ol])
    if isinstance(ol, dict):
        base = lists[ol["list"]]
        exclude = set(ol.get("exclude", []))
        return [n for n in base if n not in exclude]
    raise ValueError("bad os_list value: %r" % (ol,))


def find_all_groups():
    groups = []
    for p in REPO.rglob("scenario.yml"):
        rel = p.relative_to(REPO)
        if rel.parts[0] == "tools" or catalog.is_hidden(rel):
            continue
        groups.append(p.parent)
    return sorted(groups, key=lambda g: str(g.relative_to(REPO)))


def resolve_group(p):
    p = pathlib.Path(p)
    return p if p.is_absolute() else (REPO / p)


def load_desc(group_dir):
    return yaml.safe_load((group_dir / "scenario.yml").read_text())


def has_header(path):
    with open(path) as f:
        return f.readline() == HEADER


def collect_targets(groups, scenario_filter=None):
    """Return list of (path, content) to write for a render run."""
    targets = []
    for g in groups:
        desc = load_desc(g)
        names = expand_scenarios(desc)
        if scenario_filter is not None:
            names = [n for n in names if n in scenario_filter]
        mdir = g / "molecule"
        for n in names:
            content = render_one(g, n, header=HEADER)
            sdir = mdir / n
            targets.append((sdir / "molecule.yml", content))
    return targets


def render_cmd(groups, scenario_filter=None):
    kept = 0
    for path, content in collect_targets(groups, scenario_filter):
        if path.exists() and not has_header(path):
            # a committed hand-written file is the source of truth as long as
            # the repo carries it, tools/migrate_check.py keeps it in sync
            kept += 1
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    if kept:
        print("kept %d hand-written molecule.yml file(s)" % kept, file=sys.stderr)
    return 0


def clean_group(group_dir, warnings, scenario_filter=None):
    mdir = group_dir / "molecule"
    if not mdir.is_dir():
        return
    for sdir in sorted(mdir.iterdir()):
        if not sdir.is_dir():
            continue
        if scenario_filter is not None and sdir.name not in scenario_filter:
            continue
        mfile = sdir / "molecule.yml"
        if not mfile.exists():
            continue
        if not has_header(mfile):
            warnings.append("skipping non-generated file: %s" % mfile)
            continue
        mfile.unlink()
        initf = sdir / "__init__.py"
        if initf.exists() and initf.stat().st_size == 0:
            initf.unlink()
        try:
            sdir.rmdir()
        except OSError:
            pass
    remaining = [p for p in mdir.iterdir() if p.name != "__init__.py"]
    ginit = mdir / "__init__.py"
    if not remaining:
        if ginit.exists() and ginit.stat().st_size == 0:
            ginit.unlink()
        try:
            mdir.rmdir()
        except OSError:
            pass


def clean_cmd(groups, scenario_filter=None):
    warnings = []
    for g in groups:
        clean_group(g, warnings, scenario_filter)
    for w in warnings:
        print("warning: " + w, file=sys.stderr)
    return 0


def build_argparser():
    ap = argparse.ArgumentParser(
        description="Render molecule.yml scenario files from scenario.yml descriptors.",
        epilog=(
            "Hand-written molecule/<scenario>/molecule.yml files (no generated "
            "header) are left alone: while the repo still commits them they "
            "are the source of truth, tools/migrate_check.py verifies they "
            "match what would be rendered."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--group", action="append", default=[],
                     help="group dir to render, e.g. pg_tde/tde (repeatable)")
    ap.add_argument("--all", action="store_true",
                     help="render every dir containing a scenario.yml")
    ap.add_argument("--scenario", action="append", default=[],
                     help="restrict to this scenario dir name within the "
                          "selected groups (repeatable); scenario dir names "
                          "cover both os_list-derived os keys and explicit "
                          "'scenarios:' map keys")
    ap.add_argument("--clean", action="store_true",
                     help="remove only generated files (header present) "
                          "instead of rendering")
    return ap


def main(argv=None):
    ap = build_argparser()
    args = ap.parse_args(argv)

    if not args.group and not args.all:
        ap.error("specify --group or --all")

    if args.all:
        groups = find_all_groups()
    else:
        groups = [resolve_group(g) for g in args.group]

    scenario_filter = set(args.scenario) if args.scenario else None
    if args.clean:
        return clean_cmd(groups, scenario_filter)
    return render_cmd(groups, scenario_filter)


if __name__ == "__main__":
    sys.exit(main())
