---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-15
          - percona-postgresql-15-pgaudit
          - percona-postgresql-15-repack
          - percona-postgresql-15-wal2json
          - percona-pg-stat-monitor15
      when: ansible_distribution == "Debian"
