---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install additional packages for running tests with apt
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
      - libxml-checker-perl
      - libyaml-perl
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - lcov
      - rsync
      - zlib1g-dev
      - libssl-dev
      - libxml2-dev
      - libpq-dev
      - pkg-config
      - valgrind
      - liblz4-dev
      - liblz4-tool
      - zstd
      - libzstd-dev
      - bzip2
      - libbz2-dev
      - libyaml-dev
      - meson
  retries: 60
  delay: 10
  register: result
  until: result is not failed

- name: install Percona Platform for PostgreSQL packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql
    - percona-postgresql-13
    - percona-postgresql-all
    - percona-postgresql-client
    - percona-postgresql-client-13
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-contrib
    - percona-postgresql-plperl-13
    - percona-postgresql-plpython3-13
    - percona-postgresql-pltcl-13
    - percona-postgresql-server-dev-13
    - percona-postgresql-server-dev-all

- name: Clone pgbackrest sources
  become_user: postgres
  git:
    repo: "{{ repo }}"
    version: "{{ version }}"
    dest: /var/lib/postgresql/pgbackrest
  vars:
    repo: "{{ lookup('env', 'COMPONENT_REPO') }}"
    version: "{{ lookup('env', 'COMPONENT_VERSION') }}"

- name: Add user postgres to sudoers
  user:
    name: postgres
    groups: sudo
    append: yes

- name: Restart Postgres
  service:
    name: postgresql
    state: restarted
  register: out
